import React from 'react';
import Head from 'next/head';
import { observer } from 'mobx-react-lite';
import Layout from '../components/layout/Layout';
import SearchVin from '../components/SearchVin/SearchVin';
// import { useStore } from '../context/mainContext';

const Home = () => (
    <>
        <Head>
            <title>Vin for Win</title>
            <meta name="description" content="Generated by create next app" />
            <meta
                name="viewport"
                content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout>
            <h1 className="g-col-12">Поиск автомобиля по VIN коду</h1>
            <div style={{ textAlign: 'center' }} className="g-col-6 g-start-4">
                <span>Укажите VIN код автомобиля.</span>
            </div>
            <SearchVin />
        </Layout>
    </>
);

export default observer(Home);
