import React from 'react';
import Head from 'next/head';
import { observer } from 'mobx-react-lite';
import Overlay from '@avtopro/overlay';
import type { GetStaticProps } from 'next';
import { useTranslation } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import Preloader from '@avtopro/preloader';
import Layout from '../components/Layout/Layout';
import SearchVin from '../components/SearchVin/SearchVin';
import Parts from '../components/Parts/Parts';
import { useStore } from '../context/mainContext';

const Home = () => {
    const { step, pending } = useStore();
    const { t } = useTranslation();

    return (
        <>
            <Head>
                <title>Vin for Win</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <h1 className="g-col-12">{t('title')}</h1>
                {step == 'search' ? <SearchVin /> : <Parts />}
                {pending && (
                    <Overlay>
                        <div style={{ color: 'white', fontSize: '24px' }}>
                            <Preloader title="Пожалуйста, подождите..." />
                        </div>
                    </Overlay>
                )}
            </Layout>
        </>
    );
};

export const getStaticProps: GetStaticProps = async ({ locale }) => ({
    props: {
        ...(await serverSideTranslations(locale ?? 'ru', ['common']))
    }
});

export default observer(Home);
