import React from 'react';
import Head from 'next/head';
import { observer } from 'mobx-react-lite';
import type { GetStaticProps } from 'next';
import { useTranslation } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import Layout from '../components/Layout/Layout';
import PartsList from '../components/PartsList/PartsList';
import HOCWrapper from './HOCWrapper';

const Parts = () => {
    const { t } = useTranslation();

    return (
        <>
            <Head>
                <title>Vin for Win</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <h1 className="g-col-12">{t('title')}</h1>
                <PartsList />
            </Layout>
        </>
    );
};

export const getStaticProps: GetStaticProps = async ({ locale }) => ({
    props: {
        ...(await serverSideTranslations(locale ?? 'ru', ['common']))
    }
});

export default HOCWrapper(observer(Parts));
